url: https://adi-dogar.github.io
baseurl: 
lsi: false
safe: true
source: blog
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
